### ISSUE TITLE
Dependencies current? 

### ISSUE THREAD

**Issue by rtaylor82** [spinen/laravel-quickbooks-client#44]
I have a Laravel 8 project I'd like to use this with but have dependency errors.  Doesn't Laravel provide illuminate/database?  

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - spinen/laravel-quickbooks-client[4.0.0, ..., 4.0.3] require illuminate/database ~5.5|~6|~7 -> found illuminate/database[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - spinen/laravel-quickbooks-client 4.0.4 requires quickbooks/v3-php-sdk ^5.3.6 -> found quickbooks/v3-php-sdk[5.3.6, ..., v5.4.7.x-dev] but it conflicts with your root composer.json require (^6.0).
    - Root composer.json requires spinen/laravel-quickbooks-client ^4.0 -> satisfiable by spinen/laravel-quickbooks-client[4.0.0, ..., 4.0.4].

`

**Comment by ssfinney** [comment]
@rtaylor82 Hi there! I'm looking into just requiring laravel/framework instead of the individual illuminate modules.

However, that won't solve your issue here. You are requiring `quickbooks/v3-php-sdk` at `^6.0`, and our package locks the Quickbooks SDK at `<= 5.4.7`. We haven't tested v6 yet, so we aren't supporting it yet.

Try removing the SDK requirement from your project's composer.json, or at least lock it to less than 6.0. Thanks!

**Comment by rtaylor82** [comment]
@ssfinney Awesome!  Yeah, I'll fix the sdk version, thank you!  

Thanks for looking into the framework version require instead!
